version: '3'

networks: 
  laravel:

services:
  node:
    build:
      context: .
      dockerfile: docker/node.dockerfile
    container_name: node
    ports: 
      - "3000:3000"
    command: 'npm start'
    networks: 
      - laravel

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    container_name: ngnix
    ports: 
      - "8000:80"
    volumes: 
      - ./api:/var/www/html
    depends_on: 
      - database
      - php
    networks: 
      - laravel

  database:
    build: 
      context: .
      dockerfile: docker/mysql.dockerfile
    container_name: database
    restart: unless-stopped
    tty: true
    ports: 
      - "4306:3306"
    expose: 
      - "4306"
    environment: 
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - laravel

  composer:
    build: 
      context: .
      dockerfile: docker/composer.dockerfile
    container_name: composer
    volumes: 
      - ./api:/var/www/html
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['composer']
    networks: 
      - laravel

  php:
    build: 
        context: .
        dockerfile: docker/php.dockerfile
    container_name: php
    volumes: 
        - ./api:/var/www/html
    ports: 
        - "9000:9000"
    networks: 
      - laravel

  npm:
    image: node:13.7
    container_name: npm
    volumes: 
      - ./api:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks: 
      - laravel

  artisan:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: artisan
    volumes:
      - ./api:/var/www/html
    depends_on:
      - database
    working_dir: /var/www/html
    entrypoint: ['php', 'artisan']
    networks:
      - laravel